@echo off

@REM set CUDA_HOME=%CUDA_PATH%
@REM set DISTUTILS_USE_SDK=1

@REM set DS_BUILD_AIO=0
@REM set DS_BUILD_CUTLASS_OPS=0
@REM set DS_BUILD_EVOFORMER_ATTN=0
@REM set DS_BUILD_FP_QUANTIZER=0
@REM set DS_BUILD_GDS=0
@REM set DS_BUILD_RAGGED_DEVICE_OPS=0
@REM set DS_BUILD_SPARSE_ATTN=0
@REM set DS_BUILD_DEEP_COMPILE=0

@REM python -m build --wheel --no-isolation

set DISTUTILS_USE_SDK=1
set DS_BUILD_AIO=1
set DS_BUILD_PIN_MEMORY=1
set DS_ENABLE_NINJA=1
python -m build --wheel --no-isolation

:end